### ISSUE TITLE
Don't show the findall(!, Y) suggestion for JuliaDynamics 

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/ShowLint#17]

**Comment by Libbum** [comment]
Unsure I completely followed the arguments for and against this one actually. I'm reconsidering. So don't worry too much about this just yet!

**Comment by rikhuijzer** [comment]
Okay, thanks :). I'll leave it for now. By the way, the reason that I just planned to disable it for the organisation is because I'm affraid of making people angry when too many wrong suggestions are coming in

**Comment by Libbum** [comment]
Yeah. It'll be difficult to have this as a service to notify people of possible improvements, when they historically think of such tools as a once-in-a-blue-moon utility they use themselves.

We have trouble with inter-personal style differences concerning JuliaFormatter.jl for example, let alone the entire Julia community. Hopefully you can come up with some form of agreement with everyone once the lints are dialled in correctly. Good luck!
